# Compare SNR between kLatestCalib and calibration without bug fix

### Apr 25, 2021

## Code

In [29]:
import sys
import csv
# sys.path.insert(0,"/users/PCON0003/cond0068/.local/lib/python3.7/")
sys.path.append("/users/PAS0654/osu8354/ARA_cvmfs/root_build/lib/") # go to parent dir
sys.path.append("/users/PCON0003/cond0068/.local/lib/python3.7/site-packages/")
# sys.path.append("/users/PCON0003/cond0068/pyrex_sims/fromBen/thesis_work/pyrex-custom/analysis/custom/analysis/")
import ROOT
import math
import numpy as np
from ROOT import TH1D,TF1, gRandom, gPad, gStyle
import matplotlib as mpl
import matplotlib.pyplot as plt
from ROOT import TChain, TSelector, TTree
import os
import matplotlib.colors as mcolors
import scipy
from matplotlib.colors import LogNorm
import pandas as pd
import seaborn as sns
%matplotlib inline
# sys.path.insert(1, "/users/PAS0654/osu8354/ARA_cvmfs/source/AraRoot/analysis/ARA_analysis/SourceSearch")
# import deDisperse_util as util
import matplotlib.colors as colors

my_path_plots = os.path.abspath("./plots/")
import re

In [30]:
# mpl.use('agg') 
mpl.rcParams['text.usetex'] = True
mpl.rcParams['text.latex.unicode'] = True
mpl.rcParams['mathtext.rm'] = 'Times New Roman'
mpl.rcParams['mathtext.it'] = 'Times New Roman:italic'
mpl.rcParams['mathtext.bf'] = 'Times New Roman:bold'

mpl.rc('font', family='serif', size=12)
mpl.rcParams['xtick.labelsize'] = 14
mpl.rcParams['ytick.labelsize'] = 14
mpl.rcParams['xtick.major.size'] = 5
mpl.rcParams['ytick.major.size'] = 5

mpl.rcParams['axes.titlesize'] = 18
mpl.rcParams['axes.labelsize'] = 18
# mpl.rc('font', size=16)
mpl.rc('axes', titlesize=20)

current_palette = sns.color_palette('colorblind', 10)
import warnings
warnings.filterwarnings("ignore")

# Get data

In [59]:
data = pd.read_pickle("/users/PAS0654/osu8354/ARA_cvmfs/source/AraRoot/analysis/ARA_analysis/ARA_SourceSearch/data_util/debug.pkl")
data.tail()

    EvNum  isCalPulser                                                SNR
78    892        False  [3.180685799580516, 2.201681293062883, 4.04706...
79    903         True  [3.8946382031198534, 3.626186717628383, 18.452...
80    931        False  [3.09514531619224, 2.4301236351702395, 3.49164...
81    933        False  [4.066165348782494, 2.6592420871145688, 4.1863...
82    938        False  [3.8041603465856446, 2.1254880444936086, 7.209...

In [73]:
len(data)

83

In [102]:
SNRArr = []#[[] for i in range(16)]
for row in data.itertuples():
    SNRArr.append(row.SNR)

In [104]:
np.shape(SNRArr)

(83, 16)

In [105]:
chNames = ["SNR_ch%i"%i for i in range(16) ]

In [106]:
SNR_pd = pd.DataFrame(SNRArr, columns = chNames)

,SNR_ch0,SNR_ch1,SNR_ch2,SNR_ch3,SNR_ch4,SNR_ch5,SNR_ch6,SNR_ch7,SNR_ch8,SNR_ch9,SNR_ch10,SNR_ch11,SNR_ch12,SNR_ch13,SNR_ch14,SNR_ch15
0,3.760113,4.462455,17.992139,11.333014,14.671769,16.368769,15.927921,12.763129,5.315628,4.498093,4.001272,2.748920,3.400952,2.503550,4.495302,4.860008
1,5.010567,4.072558,17.888965,11.532375,16.734344,15.872087,15.047364,12.392645,4.023541,4.250695,3.870769,3.954107,3.599229,2.146578,4.506334,11.543971
2,3.304763,2.811971,4.821209,3.228853,4.522331,3.575098,3.104507,3.249136,4.568121,3.758511,3.904947,3.133304,3.153999,3.028577,3.496370,6.609259
3,3.814022,5.767795,20.290934,10.757895,19.323952,15.006053,14.256969,11.997253,3.917589,4.056433,4.052176,4.043237,4.583516,2.355996,3.435462,7.214575
4,5.178556,3.865915,18.908754,11.441057,17.586704,13.999903,15.593342,12.342396,4.191067,4.278803,3.376935,4.248898,4.388254,3.045287,5.385133,3.709434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,3.180686,2.201681,4.047062,3.341478,7.834834,3.400057,3.503798,4.237494,5.427883,3.351808,3.618262,3.334547,3.470916,3.052610,5.055386,7.406785
79,3.894638,3.626187,18.452499,11.380164,17.437439,15.666006,14.303283,13.849958,4.922156,3.744783,3.510407,2.893706,3.156056,2.290836,3.845879,8.060402
80,3.095145,2.430124,3.491645,3.380603,5.037949,4.648903,2.535173,3.574903,4.968669,3.692420,5.727624,2.754283,3.567193,2.428330,4.289940,4.322932
81,4.066165,2.659242,4.186321,3.095988,6.141342,3.668093,4.037957,3.225532,7.755601,3.482665,3.470789,3.437695,3.741746,2.378544,4.094855,7.439544
82,3.804160,2.125488,7.209673,2.979073,4.679387,3.673577,3.789731,3.883580,4.464142,2.523129,3.940262,2.610635,4.070700,2.074481,3.250692,2.980223